-- Seed script for common gym exercises
-- Copy and paste this into the Supabase SQL Editor

INSERT INTO exercises (name, muscle_group_id, user_id)
VALUES
  ('Dumbbell Bench Press', 1, null),
  ('Pec Deck Fly', 1, null),
  ('Push-ups', 1, null),
  ('Machine Chest Press', 1, null),
  ('Incline Barbell Bench Press', 2, null),
  ('Incline Cable Fly', 2, null),
  ('Incline Machine Press', 2, null),
  ('Low-to-High Cable Crossover', 2, null),
  ('Decline Barbell Bench Press', 3, null),
  ('Decline Dumbbell Bench Press', 3, null),
  ('High-to-Low Cable Crossover', 3, null),
  ('Chest Dips', 3, null),
  ('Decline Machine Press', 3, null),
  ('Lat Pulldown (Wide Grip)', 4, null),
  ('Lat Pulldown (Close Grip)', 4, null),
  ('Dumbbell Row', 4, null),
  ('Straight Arm Pulldown', 4, null),
  ('T-Bar Row', 4, null),
  ('Machine Row', 4, null),
  ('Reverse Pec Deck', 5, null),
  ('Rear Delt Cable Fly', 5, null),
  ('Back Extension', 6, null),
  ('Good Mornings', 6, null),
  ('Dumbbell Shrugs', 7, null),
  ('Barbell Shrugs', 7, null),
  ('Farmer Walk', 7, null),
  ('Reverse Machine Fly', 8, null),
  ('Dumbbell Reverse Fly', 8, null),
  ('Dumbbell Shoulder Press', 9, null),
  ('Machine Shoulder Press', 9, null),
  ('Front Dumbbell Raise', 9, null),
  ('Arnold Press', 9, null),
  ('Cable Lateral Raise', 10, null),
  ('Machine Lateral Raise', 10, null),
  ('Barbell Front Squat', 11, null),
  ('Hack Squat', 11, null),
  ('Bulgarian Split Squat', 11, null),
  ('Lunges', 11, null),
  ('Goblet Squat', 11, null),
  ('Stiff-Leg Deadlift', 12, null),
  ('Glute-Ham Raise', 12, null),
  ('Glute Kickback', 13, null),
  ('Cable Pull Through', 13, null),
  ('Sumo Deadlift', 13, null),
  ('Seated Calf Raise', 14, null),
  ('Leg Press Calf Raise', 14, null),
  ('Hip Abductor Machine', 15, null),
  ('Cable Hip Abduction', 15, null),
  ('Hip Adductor Machine', 16, null),
  ('Preacher Curl', 17, null),
  ('EZ Bar Curl', 17, null),
  ('Incline Dumbbell Curl', 17, null),
  ('Cable Curl', 17, null),
  ('Concentration Curl', 17, null),
  ('Skull Crushers', 18, null),
  ('Close Grip Bench Press', 18, null),
  ('Tricep Dips', 18, null),
  ('Dumbbell Tricep Kickback', 18, null),
  ('Machine Tricep Extension', 18, null),
  ('Wrist Curls', 19, null),
  ('Reverse Wrist Curls', 19, null),
  ('Reverse Barbell Curl', 19, null),
  ('Dead Hangs', 19, null),
  ('Crunches', 20, null),
  ('Sit-ups', 20, null),
  ('Plank', 20, null),
  ('Cable Crunch', 20, null),
  ('Ab Wheel Rollout', 20, null),
  ('Woodchoppers', 21, null),
  ('Russian Twists', 21, null),
  ('Bicycle Crunches', 21, null),
  ('Side Plank', 21, null),
  ('Clean and Jerk', 22, null),
  ('Snatch', 22, null),
  ('Kettlebell Swings', 22, null),
  ('Burpees', 22, null)
ON CONFLICT DO NOTHING;
