INSERT INTO exercises (name, hit_area) VALUES
  -- Chest
  ('Barbell Bench Press', 'Chest'),
  ('Incline Barbell Bench Press', 'Chest'),
  ('Decline Bench Press', 'Chest'),
  ('Dumbbell Bench Press', 'Chest'),
  ('Incline Dumbbell Press', 'Chest'),
  ('Decline Dumbbell Press', 'Chest'),
  ('Dumbbell Flyes', 'Chest'),
  ('Incline Dumbbell Flyes', 'Chest'),
  ('Cable Crossover', 'Chest'),
  ('Low-to-High Cable Fly', 'Chest'),
  ('Pec Deck Machine', 'Chest'),
  ('Push-Ups', 'Chest'),
  ('Incline Push-Ups', 'Chest'),
  ('Dips (Chest Focus)', 'Chest'),
  ('Landmine Press', 'Chest'),
  ('Smith Machine Bench Press', 'Chest'),

  -- Back
  ('Deadlift', 'Back'),
  ('Sumo Deadlift', 'Back'),
  ('Trap Bar Deadlift', 'Back'),
  ('Pull-Ups', 'Back'),
  ('Chin-Ups', 'Back'),
  ('Neutral-Grip Pull-Ups', 'Back'),
  ('Lat Pulldown', 'Back'),
  ('Close-Grip Lat Pulldown', 'Back'),
  ('Barbell Row', 'Back'),
  ('Pendlay Row', 'Back'),
  ('Dumbbell Row', 'Back'),
  ('T-Bar Row', 'Back'),
  ('Seated Cable Row', 'Back'),
  ('Chest-Supported Row', 'Back'),
  ('Face Pulls', 'Back'),
  ('Straight-Arm Pulldown', 'Back'),
  ('Rack Pulls', 'Back'),
  ('Good Mornings', 'Back'),
  ('Inverted Row', 'Back'),

  -- Shoulders
  ('Overhead Press', 'Shoulders'),
  ('Push Press', 'Shoulders'),
  ('Dumbbell Shoulder Press', 'Shoulders'),
  ('Arnold Press', 'Shoulders'),
  ('Seated Dumbbell Press', 'Shoulders'),
  ('Lateral Raises', 'Shoulders'),
  ('Cable Lateral Raise', 'Shoulders'),
  ('Front Raises', 'Shoulders'),
  ('Rear Delt Flyes', 'Shoulders'),
  ('Reverse Pec Deck', 'Shoulders'),
  ('Upright Row', 'Shoulders'),
  ('Shrugs', 'Shoulders'),
  ('Dumbbell Shrugs', 'Shoulders'),

  -- Quads
  ('Barbell Back Squat', 'Quads'),
  ('Front Squat', 'Quads'),
  ('Zercher Squat', 'Quads'),
  ('Leg Press', 'Quads'),
  ('Hack Squat', 'Quads'),
  ('Bulgarian Split Squat', 'Quads'),
  ('Walking Lunges', 'Quads'),
  ('Reverse Lunges', 'Quads'),
  ('Leg Extension', 'Quads'),
  ('Goblet Squat', 'Quads'),
  ('Sissy Squat', 'Quads'),
  ('Step-Ups', 'Quads'),
  ('Smith Machine Squat', 'Quads'),
  ('Box Squat', 'Quads'),

  -- Hamstrings / Glutes
  ('Romanian Deadlift', 'Hamstrings'),
  ('Stiff-Leg Deadlift', 'Hamstrings'),
  ('Leg Curl (Lying)', 'Hamstrings'),
  ('Leg Curl (Seated)', 'Hamstrings'),
  ('Nordic Curl', 'Hamstrings'),
  ('Single-Leg RDL', 'Hamstrings'),
  ('Hip Thrust', 'Glutes'),
  ('Glute Bridge', 'Glutes'),
  ('Cable Pull-Through', 'Glutes'),
  ('Cable Kickback (Glute)', 'Glutes'),
  ('Hip Abduction Machine', 'Glutes'),
  ('Hip Adduction Machine', 'Glutes'),

  -- Calves
  ('Standing Calf Raises', 'Calves'),
  ('Seated Calf Raises', 'Calves'),
  ('Leg Press Calf Raise', 'Calves'),
  ('Donkey Calf Raise', 'Calves'),
  ('Single-Leg Calf Raise', 'Calves'),

  -- Biceps
  ('Barbell Curl', 'Biceps'),
  ('Dumbbell Curl', 'Biceps'),
  ('Hammer Curl', 'Biceps'),
  ('Preacher Curl', 'Biceps'),
  ('Concentration Curl', 'Biceps'),
  ('Cable Curl', 'Biceps'),
  ('Incline Dumbbell Curl', 'Biceps'),
  ('EZ-Bar Curl', 'Biceps'),
  ('Spider Curl', 'Biceps'),
  ('Zottman Curl', 'Biceps'),
  ('Reverse Curl', 'Biceps'),
  ('21s Bicep Curl', 'Biceps'),

  -- Triceps
  ('Close-Grip Bench Press', 'Triceps'),
  ('Tricep Pushdown', 'Triceps'),
  ('Rope Pushdown', 'Triceps'),
  ('Overhead Tricep Extension', 'Triceps'),
  ('Dumbbell Overhead Extension', 'Triceps'),
  ('Skull Crushers', 'Triceps'),
  ('Dips (Tricep Focus)', 'Triceps'),
  ('Cable Kickback', 'Triceps'),
  ('Diamond Push-Ups', 'Triceps'),
  ('JM Press', 'Triceps'),

  -- Core
  ('Plank', 'Core'),
  ('Side Plank', 'Core'),
  ('Hanging Leg Raise', 'Core'),
  ('Hanging Knee Raise', 'Core'),
  ('Cable Crunch', 'Core'),
  ('Ab Wheel Rollout', 'Core'),
  ('Russian Twist', 'Core'),
  ('Sit-Ups', 'Core'),
  ('Bicycle Crunch', 'Core'),
  ('Mountain Climbers', 'Core'),
  ('V-Ups', 'Core'),
  ('Dead Bug', 'Core'),
  ('Bird Dog', 'Core'),
  ('Pallof Press', 'Core'),
  ('Woodchopper', 'Core'),
  ('Back Extension', 'Core'),

  -- Full Body / Compound / Conditioning
  ('Clean and Jerk', 'Full Body'),
  ('Snatch', 'Full Body'),
  ('Power Clean', 'Full Body'),
  ('Kettlebell Swing', 'Full Body'),
  ('Farmer''s Carry', 'Full Body'),
  ('Thruster', 'Full Body'),
  ('Burpees', 'Full Body'),
  ('Wall Ball', 'Full Body'),
  ('Sled Push', 'Full Body'),
  ('Sled Pull', 'Full Body'),
  ('Battle Ropes', 'Full Body'),
  ('Box Jump', 'Full Body'),
  ('Jump Rope', 'Full Body'),
  ('Rowing Machine', 'Full Body'),
  ('Assault Bike', 'Full Body'),
  ('Treadmill Running', 'Full Body'),
  ('Stationary Cycling', 'Full Body')
ON CONFLICT (name) DO NOTHING;
