INSERT INTO exercises (name, muscle_group_id)
SELECT v.exercise_name, mg.id
FROM (VALUES
  -- Chest
  ('Barbell Bench Press', 'Mid Chest'),
  ('Incline Barbell Bench Press', 'Upper Chest'),
  ('Decline Bench Press', 'Lower Chest'),
  ('Dumbbell Bench Press', 'Mid Chest'),
  ('Incline Dumbbell Press', 'Upper Chest'),
  ('Decline Dumbbell Press', 'Lower Chest'),
  ('Dumbbell Flyes', 'Mid Chest'),
  ('Incline Dumbbell Flyes', 'Upper Chest'),
  ('Cable Crossover', 'Mid Chest'),
  ('Low-to-High Cable Fly', 'Upper Chest'),
  ('Pec Deck Machine', 'Mid Chest'),
  ('Push-Ups', 'Mid Chest'),
  ('Incline Push-Ups', 'Lower Chest'),
  ('Dips (Chest Focus)', 'Lower Chest'),
  ('Landmine Press', 'Upper Chest'),
  ('Smith Machine Bench Press', 'Mid Chest'),

  -- Back
  ('Deadlift', 'Lower Back'),
  ('Sumo Deadlift', 'Lower Back'),
  ('Trap Bar Deadlift', 'Lower Back'),
  ('Pull-Ups', 'Lats'),
  ('Chin-Ups', 'Lats'),
  ('Neutral-Grip Pull-Ups', 'Lats'),
  ('Lat Pulldown', 'Lats'),
  ('Close-Grip Lat Pulldown', 'Lats'),
  ('Barbell Row', 'Lats'),
  ('Pendlay Row', 'Lats'),
  ('Dumbbell Row', 'Lats'),
  ('T-Bar Row', 'Rhomboids'),
  ('Seated Cable Row', 'Rhomboids'),
  ('Chest-Supported Row', 'Rhomboids'),
  ('Face Pulls', 'Rear Delts'),
  ('Straight-Arm Pulldown', 'Lats'),
  ('Rack Pulls', 'Lower Back'),
  ('Good Mornings', 'Lower Back'),
  ('Inverted Row', 'Lats'),

  -- Shoulders
  ('Overhead Press', 'Front Delts'),
  ('Push Press', 'Front Delts'),
  ('Dumbbell Shoulder Press', 'Front Delts'),
  ('Arnold Press', 'Front Delts'),
  ('Seated Dumbbell Press', 'Front Delts'),
  ('Lateral Raises', 'Side Delts'),
  ('Cable Lateral Raise', 'Side Delts'),
  ('Front Raises', 'Front Delts'),
  ('Rear Delt Flyes', 'Rear Delts'),
  ('Reverse Pec Deck', 'Rear Delts'),
  ('Upright Row', 'Traps'),
  ('Shrugs', 'Traps'),
  ('Dumbbell Shrugs', 'Traps'),

  -- Quads
  ('Barbell Back Squat', 'Quads'),
  ('Front Squat', 'Quads'),
  ('Zercher Squat', 'Quads'),
  ('Leg Press', 'Quads'),
  ('Hack Squat', 'Quads'),
  ('Bulgarian Split Squat', 'Quads'),
  ('Walking Lunges', 'Quads'),
  ('Reverse Lunges', 'Quads'),
  ('Leg Extension', 'Quads'),
  ('Goblet Squat', 'Quads'),
  ('Sissy Squat', 'Quads'),
  ('Step-Ups', 'Quads'),
  ('Smith Machine Squat', 'Quads'),
  ('Box Squat', 'Quads'),

  -- Hamstrings / Glutes / Abductors / Adductors
  ('Romanian Deadlift', 'Hamstrings'),
  ('Stiff-Leg Deadlift', 'Hamstrings'),
  ('Leg Curl (Lying)', 'Hamstrings'),
  ('Leg Curl (Seated)', 'Hamstrings'),
  ('Nordic Curl', 'Hamstrings'),
  ('Single-Leg RDL', 'Hamstrings'),
  ('Hip Thrust', 'Glutes'),
  ('Glute Bridge', 'Glutes'),
  ('Cable Pull-Through', 'Glutes'),
  ('Cable Kickback (Glute)', 'Glutes'),
  ('Hip Abduction Machine', 'Abductors'),
  ('Hip Adduction Machine', 'Adductors'),

  -- Calves
  ('Standing Calf Raises', 'Calves'),
  ('Seated Calf Raises', 'Calves'),
  ('Leg Press Calf Raise', 'Calves'),
  ('Donkey Calf Raise', 'Calves'),
  ('Single-Leg Calf Raise', 'Calves'),

  -- Biceps / Forearms
  ('Barbell Curl', 'Biceps'),
  ('Dumbbell Curl', 'Biceps'),
  ('Hammer Curl', 'Biceps'),
  ('Preacher Curl', 'Biceps'),
  ('Concentration Curl', 'Biceps'),
  ('Cable Curl', 'Biceps'),
  ('Incline Dumbbell Curl', 'Biceps'),
  ('EZ-Bar Curl', 'Biceps'),
  ('Spider Curl', 'Biceps'),
  ('Zottman Curl', 'Forearms'),
  ('Reverse Curl', 'Forearms'),
  ('21s Bicep Curl', 'Biceps'),

  -- Triceps
  ('Close-Grip Bench Press', 'Triceps'),
  ('Tricep Pushdown', 'Triceps'),
  ('Rope Pushdown', 'Triceps'),
  ('Overhead Tricep Extension', 'Triceps'),
  ('Dumbbell Overhead Extension', 'Triceps'),
  ('Skull Crushers', 'Triceps'),
  ('Dips (Tricep Focus)', 'Triceps'),
  ('Cable Kickback', 'Triceps'),
  ('Diamond Push-Ups', 'Triceps'),
  ('JM Press', 'Triceps'),

  -- Core (Abs / Obliques / Lower Back)
  ('Plank', 'Abs'),
  ('Side Plank', 'Obliques'),
  ('Hanging Leg Raise', 'Abs'),
  ('Hanging Knee Raise', 'Abs'),
  ('Cable Crunch', 'Abs'),
  ('Ab Wheel Rollout', 'Abs'),
  ('Russian Twist', 'Obliques'),
  ('Sit-Ups', 'Abs'),
  ('Bicycle Crunch', 'Obliques'),
  ('Mountain Climbers', 'Abs'),
  ('V-Ups', 'Abs'),
  ('Dead Bug', 'Abs'),
  ('Bird Dog', 'Lower Back'),
  ('Pallof Press', 'Obliques'),
  ('Woodchopper', 'Obliques'),
  ('Back Extension', 'Lower Back'),

  -- Full Body / Compound / Conditioning
  ('Clean and Jerk', 'Full Body'),
  ('Snatch', 'Full Body'),
  ('Power Clean', 'Full Body'),
  ('Kettlebell Swing', 'Full Body'),
  ('Farmer''s Carry', 'Full Body'),
  ('Thruster', 'Full Body'),
  ('Burpees', 'Full Body'),
  ('Wall Ball', 'Full Body'),
  ('Sled Push', 'Full Body'),
  ('Sled Pull', 'Full Body'),
  ('Battle Ropes', 'Full Body'),
  ('Box Jump', 'Full Body'),
  ('Jump Rope', 'Full Body'),
  ('Rowing Machine', 'Full Body'),
  ('Assault Bike', 'Full Body'),
  ('Treadmill Running', 'Full Body'),
  ('Stationary Cycling', 'Full Body')
) AS v(exercise_name, hit_area)
JOIN muscle_groups mg ON mg.name = v.hit_area
ON CONFLICT (name) DO NOTHING;